### ISSUE TITLE
Log directory not resolved relative to behat.yml directory

### ISSUE THREAD

**Issue by kasperg** [FriendsOfBehat/MinkDebugExtension#15]
Thanks for your work. I have been trying out a bit and it has already proven very helpful!

A minor issue: The documentation says that the log directory can be relative to the behat.yml directory. I cannot get this to work in pratice.

You can see my setup [here](https://github.com/DBCDK/biblo-admin/blob/feature/test-bootstrap/tests/behat.yml#L24).

In short I have a directory in the root of my repo called `tests` and this contains `behat.yml`. Behat is in `vendor/bin/behat`. I want to keep the test logs in `tests/logs`.

If I set `directory` to `logs` and run `vendor/bin/behat -c tests/behat.yml` I get the error "Failed while trying to write log in "logs/behat-20160229123516.log" because the user does not have permissions to create a new directory in the same folder at `vendor` and `tests`.

If I set `directory` to `tests/logs/` things work fine.

**Comment by kasperg** [comment]
For the record: Using [path variables](http://docs.behat.org/en/v3.0/guides/5.suites.html#suite-paths) also works. In my case that would be `directory: %paths.base%/logs`. Perhaps the best way to handle this would be to update the documentation?

**Comment by pjedrzejewski** [comment]
@kasperg :+1: Would you find a moment to open a PR with doc update? That would be awesome!

**Comment by kasperg** [comment]
Fixed in #16.

**Comment by pjedrzejewski** [comment]
@kasperg Awesome, thanks! :)
