### ISSUE TITLE
Trouble getting the imgur integration set up

### ISSUE THREAD

**Issue by kostajh** [FriendsOfBehat/MinkDebugExtension#18]
Hi,

First, thanks for this great extension!

I'm having trouble getting the Imgur integration set up. I couldn't figure out how to encrypt my Imgur key using `travis env set` or `travis encrypt` or the settings UI, so I ended up placing it in plain text: `export IMGUR_API_KEY=somekey`. 

In the Travis build output, I see this:

```
Uploading screenshots...
/home/travis/build/example/tests/build/logs/behat-20160309090159.png - 
/home/travis/build/example/tests/build/logs/behat-20160309090204.png - 
/home/travis/build/example/tests/build/logs/behat-20160309090211.png - 
```

But no Imgur links are output. Maybe I've got the wrong Application type set up in Imgur? I went with "Anonymous application" for generating the API keys.

Any ideas?

**Comment by pamil** [comment]
Hello! Sorry for getting back to this so late, I've got no idea, but replacing the following lines from `upload-screenshots` file:

``` bash
url=`curl -s -# -F "image"=@"$image" -F "key"="$IMGUR_API_KEY" imgur.com/api/upload.xml \
     | grep -Eo '<[a-z_]+>http[^<]+' \
     | sed 's/^<.\|_./\U&/g;s/_/ /;s/<\(.*\)>/\x1B[0;34m\1:\x1B[0m /' \
     | grep Original \
     | awk '{ print $3 }'`
```

with 

``` bash
url=`curl -s -# -F "image"=@"$image" -F "key"="$IMGUR_API_KEY" imgur.com/api/upload.xml`
```

May help and show the error message from imgur.

**Comment by kostajh** [comment]
@pamil thanks! I'm getting:

```
<error><error_code>1004</error_code><error_msg>Invalid API Key</error_msg></error>
```

I'm not sure how to obtain a valid API key. Any ideas?

**Comment by pamil** [comment]
The currently recommended way is to use GitHub Actions and their upload-artifact action, the script is removed in v2.0 release.
